# Generated by Django 5.0.2 on 2026-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_supplier',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên đối tác'),
        ),
    ]
