# Generated by Django 5.0.2 on 2026-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_stockitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=0, verbose_name='Ngưỡng cảnh báo tồn kho'),
        ),
    ]
