# Generated by Django 5.0.2 on 2026-03-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='held_quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng đang giữ đơn'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng thực tế'),
        ),
    ]
