# Generated by Django 5.0.2 on 2026-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_stockitem_held_quantity_stockitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='incoming_quantity',
            field=models.IntegerField(default=0, verbose_name='Số lượng sắp nhập về'),
        ),
    ]
