# Generated by Django 5.0.2 on 2026-03-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('RECEIVABLE', 'Phải thu (Khách nợ)'), ('PAYABLE', 'Phải trả (Nợ NCC)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('is_settlement', models.BooleanField(default=False, verbose_name='Là khoản thanh toán')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_entries', to='accounts.customer')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.purchaseorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('RECEIVABLE', 'Phải thu (Khách nợ)'), ('PAYABLE', 'Phải trả (Nợ NCC)')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thanh toán')),
                ('payment_date', models.DateField(verbose_name='Ngày thanh toán')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='accounts.customer')),
            ],
        ),
    ]
