# Generated by Django 5.0.2 on 2026-03-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='debt.debtentry'),
        ),
    ]
