# Generated by Django 5.0.2 on 2026-03-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_remove_customer_is_supplier_and_more'),
        ('debt', '0002_debtentry_parent_entry'),
        ('orders', '0004_alter_salesorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_entries', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='debtentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='debt.debtentry'),
        ),
        migrations.AlterField(
            model_name='debtentry',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='debtentry',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.salesorder'),
        ),
    ]
