# Generated by Django 5.0.2 on 2026-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0003_alter_debtentry_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtentry',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ngày ghi'),
        ),
    ]
