# Generated by Django 5.0.2 on 2026-03-31 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0004_debtentry_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtentry',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='debt.settlement'),
        ),
    ]
