# Generated by Django 5.0.2 on 2026-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0005_debtentry_settlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtentry',
            options={'verbose_name': 'Bản ghi công nợ', 'verbose_name_plural': 'Bản ghi công nợ'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'Phiếu quyết toán', 'verbose_name_plural': 'Phiếu quyết toán'},
        ),
        migrations.AlterField(
            model_name='settlement',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
