# Generated by Django 5.0.2 on 2026-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
    ]
