# Generated by Django 5.0.2 on 2026-03-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_remove_customer_is_supplier_and_more'),
        ('orders', '0002_alter_purchaseorderline_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer', verbose_name='Nhà cung cấp'),
        ),
    ]
