# Generated by Django 5.0.2 on 2026-03-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_remove_customer_is_supplier_and_more'),
        ('orders', '0003_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer', verbose_name='Đối tác'),
        ),
    ]
