# Generated by Django 5.0.2 on 2026-03-20 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchaseorder_paid_amount_salesorder_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nhập hàng'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đã thanh toán (tại quầy)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đặt hàng'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đã thanh toán (tại quầy)'),
        ),
    ]
