# Generated by Django 5.0.2 on 2026-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Đã thanh toán (tại quầy)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Đã thanh toán (tại quầy)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền'),
        ),
    ]
